image: "gradle:alpine"

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

before_script:
  - "export GRADLE_USER_HOME=`pwd`/.gradle"

build:
  image: "maven:3-jdk-11"
  script:
    - "./gradlew --build-cache build"
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: "push"
    paths:
      - "build"
      - ".gradle"
