image: "maven:3-jdk-11"

cache:
  paths:
    - "maven.repository/"

variables:
  MAVEN_OPTS: "--batch-mode -Dmaven.repo.local=maven.repository"

build:
  image: "maven:3-jdk-11"
  script:
    - "mvn compile"
