image: gradle:jdk16

stages:
  - build
  - test
  - deploy

variables:
  GRADLE_OPTS: "-Dmaven.repo.local=${CI_PROJECT_DIR}/.m2/repository"
  GRADLE_USER_HOME: "${CI_PROJECT_DIR}/.gradle"

build:
  stage: build
  script:
    - "gradle --build-cache assemble shadowJar"
    - "gradle check"
    - "gradle publish"
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: pull-push
    paths:
      - "*/build"
      - ".m2/repository"
  artifacts:
    paths:
      - ".gradle"
      - "*/build/libs/*.jar"
    expire_in: 1 week

pages:
  stage: deploy
  script:
    - "gradle javadoc"
    - "mv src/site public"
    - "mkdir -p public/javadoc"
    - "mv core/build/docs/javadoc public/javadoc/core"
    - "mv paper/build/docs/javadoc public/javadoc/paper"
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: pull
    paths:
      - "*/build"
      - ".m2/repository"
  artifacts:
    paths:
      - "public"
  only:
    - master
