name: "Calibre"
description: "Advanced, scalable and modular gun plugin for Paper"
author: "aecsocket"
version: "1.0"
api-version: "1.13"
main: "me.aecsocket.calibre.CalibrePlugin"
depend: [ "ProtocolLib" ]