[versions]

minecraft = "1.18.2"

alexandria = "0.3.3-SNAPSHOT"
bstats = "2.2.1"
packetEvents = "2.0-SNAPSHOT"

[libraries]

alexandriaCore = { group = "com.github.aecsocket.alexandria", name = "alexandria-core", version.ref = "alexandria" }
alexandriaPaper = { group = "com.github.aecsocket.alexandria", name = "alexandria-paper", version.ref = "alexandria" }

bstatsPaper = { group = "org.bstats", name = "bstats-bukkit", version.ref = "bstats" }

packetEvents = { group = "com.github.retrooper", name = "packetevents", version.ref = "packetEvents" }
