name: "Build"

on:
  push:
    branches: [ "**" ]
    tags-ignore: [ "**" ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: gradle/wrapper-validation-action@v1
      - uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: "adopt"
      - uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ secrets.CACHE_VERSION }}-${{ hashFiles('**/*.gradle.kts', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-${{ secrets.CACHE_VERSION }}-

      - name: "Build"
        run: ./gradlew build
      - name: "Upload test results"
        uses: actions/upload-artifact@v3
        with:
          name: "test-results-${{ runner.os }}"
          path: |
            */build/reports/*
      - name: "Upload JAR"
        uses: actions/upload-artifact@v3
        with:
          name: "jar"
          path: |
            */build
