name: "Calibre"
description: "Advanced, scalable and modular gun framework - Paper implementation"
author: "aecsocket"
version: "1.0"
api-version: "1.16"
main: "me.aecsocket.calibre.CalibrePlugin"
depend: [ "ProtocolLib" ]