# TODO https://github.com/Minecrell/plugin-yml when it adds `libraries` support
name: "Calibre"
version: "1.1"
description: "Platform-agnostic, customisable and modular gun library"
url: "https://gitlab.com/aecsocket/calibre"
author: "aecsocket"

main: "com.gitlab.aecsocket.calibre.paper.CalibrePlugin"
api-version: "1.17"

depend:
  - "Minecommons"
  - "Sokol"
  - "ProtocolLib"
