name: "Calibre"
description: "@description@"
main: "@group@.paper.Calibre"
version: "@version@"
api-version: "1.19"
authors: [ "aecsocket" ]
website: "https://phosphorous.gitlab.io/calibre"

depend: [ "KtRuntime", "Alexandria", "Sokol" ]
