name: "Calibre"
description: "Advanced, scalable and modular gun framework - Paper implementation"
author: "aecsocket"
version: "${project.version}"
api-version: "1.16"
main: "com.gitlab.aecsocket.calibre.paper.CalibrePlugin"
depend: [ "ProtocolLib" ]